### ISSUE TITLE
Upgrade PHP code to fit PHP8

### ISSUE THREAD

**Issue by Sh11td0wn** [epinna/weevely3#159] opened 2023-02-06 01:52 UTC
Upgrade PHP code to fit PHP8 dialect.

Example: replace 'create_function()' to PHP anonymous function.

**Comment by ZanyMonk** [comment] 2023-06-09 17:18
Duplicate of #151

**Comment by stish834** [comment] 2023-06-10 15:12
**Not working in *8 versions please upgrade**

**Comment by ZanyMonk** [comment] 2023-06-10 15:51
_*PR submitted please review_

**Closed** 2023-06-11 15:19 UTC
